- name: Set index variables
  set_fact:
    idx: "{{ ansible_play_hosts.index(inventory_hostname) }}"
    idxlist: "{{ range(0, ansible_play_hosts|length)|list }}"
    num_master_hosts: "{{ ansible_play_hosts | length }}"

- debug:
    msg="exp id = {{ experiment_id }}  idx = {{ idx }} idxlist = {{ idxlist }}"

- name: Create log4j2 configuration file
  template:
    src=log4j2.yaml.j2
    dest={{ log_dir }}/zephmaster{{ item }}_log4j2.yaml
    mode='preserve'
  when: item|int % num_master_hosts|int == idx|int
  loop: '{{ idxlist }}'

- name: set java agent for prometheus (for use_monitoring)
  set_fact:
    javaagent_jmx_exporter_prometheus: '-javaagent:"{{monitoring_dir}}/jmx_prometheus_javaagent.jar=11001:{{ monitoring_dir }}/jmx_config.yml"'
  when: use_monitoring

- name: set java agent for prometheus (for not use_monitoring)
  set_fact:
    javaagent_jmx_exporter_prometheus: ""
  when: not use_monitoring

- name: Create Unit File
  become: yes
  template:
    src=zephmaster.service.j2
    dest=/lib/systemd/system/zephmaster{{ item }}.service
    mode=644
  notify:
  - reload systemctl
  when: item|int % num_master_hosts|int == idx|int
  loop: '{{ idxlist }}'

- name: Start Zeph Master
  become: yes
  service: name=zephmaster{{ item }}.service state=started enabled=yes
  when: item|int % num_master_hosts|int == idx|int
  loop: '{{ idxlist }}'
