[package]
name = "secure-aggregation-dream"
version = "0.0.1"
authors = ["nicok"]
edition = "2018"


[dependencies]
aes = "0.3.2"
byteorder = "1.3.1"
jni = "0.15.0"
multimap = "0.8.0"

[lib]
crate_type = ["cdylib"]
